# Generated by Django 2.2.1 on 2019-06-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example',
            table='Example',
        ),
    ]
