# Generated by Django 2.2.1 on 2019-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_example_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
